export const voters: any[] = [
  {
    id: 1,
    firstName: "Brynna",
    lastName: "Goranov",
    age: 78,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 2,
    firstName: "Tracey",
    lastName: "Manz",
    age: 79,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 3,
    firstName: "Margeaux",
    lastName: "Frape",
    age: 34,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 4,
    firstName: "Ab",
    lastName: "Webb-Bowen",
    age: 27,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 5,
    firstName: "Walden",
    lastName: "Japp",
    age: 80,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 6,
    firstName: "Goraud",
    lastName: "Warboys",
    age: 73,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 7,
    firstName: "Vassili",
    lastName: "MacCrann",
    age: 87,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 8,
    firstName: "Elicia",
    lastName: "Clowton",
    age: 47,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 9,
    firstName: "Olav",
    lastName: "Kleinstein",
    age: 74,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 10,
    firstName: "Juliane",
    lastName: "Plank",
    age: 90,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 11,
    firstName: "Thia",
    lastName: "Scrimshire",
    age: 81,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 12,
    firstName: "Nollie",
    lastName: "Walklot",
    age: 31,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 13,
    firstName: "Sidnee",
    lastName: "Remer",
    age: 74,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 14,
    firstName: "Cacilie",
    lastName: "Lydall",
    age: 75,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 15,
    firstName: "Jared",
    lastName: "Robez",
    age: 47,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 16,
    firstName: "Terrie",
    lastName: "Keble",
    age: 78,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 17,
    firstName: "Timofei",
    lastName: "Nairy",
    age: 18,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 18,
    firstName: "Holmes",
    lastName: "McColl",
    age: 18,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 19,
    firstName: "Allyn",
    lastName: "Patek",
    age: 43,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 20,
    firstName: "Dermot",
    lastName: "Fairfoull",
    age: 55,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 21,
    firstName: "Archie",
    lastName: "Ponnsett",
    age: 75,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 22,
    firstName: "Barnard",
    lastName: "Poytheras",
    age: 37,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 23,
    firstName: "Montague",
    lastName: "Tennant",
    age: 75,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 24,
    firstName: "Lorne",
    lastName: "Guerreru",
    age: 71,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 25,
    firstName: "Royce",
    lastName: "Craiker",
    age: 90,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 26,
    firstName: "Stearn",
    lastName: "Mandeville",
    age: 88,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 27,
    firstName: "Dominique",
    lastName: "Way",
    age: 94,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 28,
    firstName: "Alfredo",
    lastName: "Janas",
    age: 60,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 29,
    firstName: "Sherrie",
    lastName: "Dillaway",
    age: 37,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 30,
    firstName: "Noland",
    lastName: "Seckom",
    age: 85,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 31,
    firstName: "Eleanora",
    lastName: "Stearn",
    age: 56,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 32,
    firstName: "Kata",
    lastName: "Whitcher",
    age: 57,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 33,
    firstName: "Ignazio",
    lastName: "Matuszynski",
    age: 79,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 34,
    firstName: "Free",
    lastName: "Dennant",
    age: 51,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 35,
    firstName: "Nestor",
    lastName: "Piken",
    age: 75,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 36,
    firstName: "Shelton",
    lastName: "Blampied",
    age: 52,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 37,
    firstName: "Retha",
    lastName: "Mattessen",
    age: 84,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 38,
    firstName: "Nona",
    lastName: "Clayworth",
    age: 57,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 39,
    firstName: "Daisi",
    lastName: "Ruckert",
    age: 21,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 40,
    firstName: "Clemmy",
    lastName: "Pawellek",
    age: 64,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 41,
    firstName: "Johnny",
    lastName: "Boustead",
    age: 45,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 42,
    firstName: "Gert",
    lastName: "Churn",
    age: 40,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 43,
    firstName: "Elsie",
    lastName: "Autrie",
    age: 63,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 44,
    firstName: "Ladonna",
    lastName: "Domeny",
    age: 18,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 45,
    firstName: "Mohandas",
    lastName: "Bullingham",
    age: 20,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 46,
    firstName: "Fancie",
    lastName: "Piercy",
    age: 46,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 47,
    firstName: "Urban",
    lastName: "Hedney",
    age: 96,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 48,
    firstName: "Yalonda",
    lastName: "Edghinn",
    age: 45,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 49,
    firstName: "Webster",
    lastName: "Belvard",
    age: 98,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 50,
    firstName: "Jeane",
    lastName: "Rousby",
    age: 46,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 51,
    firstName: "Fayth",
    lastName: "Harmar",
    age: 76,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 52,
    firstName: "Fredrick",
    lastName: "Edworthye",
    age: 85,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 53,
    firstName: "Arturo",
    lastName: "Trippitt",
    age: 91,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 54,
    firstName: "Rustie",
    lastName: "Duran",
    age: 79,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 55,
    firstName: "Pembroke",
    lastName: "Risebarer",
    age: 60,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 56,
    firstName: "Graeme",
    lastName: "Chelnam",
    age: 87,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 57,
    firstName: "Gilemette",
    lastName: "Boagey",
    age: 92,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 58,
    firstName: "Witty",
    lastName: "Traise",
    age: 96,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 59,
    firstName: "Garrick",
    lastName: "Gallehock",
    age: 41,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 60,
    firstName: "Lorne",
    lastName: "Simeoli",
    age: 30,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 61,
    firstName: "Kimball",
    lastName: "Tender",
    age: 60,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 62,
    firstName: "Freddi",
    lastName: "Stanistrete",
    age: 36,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 63,
    firstName: "Manolo",
    lastName: "Duran",
    age: 35,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 64,
    firstName: "Steffi",
    lastName: "Kier",
    age: 87,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 65,
    firstName: "Eward",
    lastName: "Yakushkev",
    age: 83,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 66,
    firstName: "Leila",
    lastName: "Ironmonger",
    age: 55,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 67,
    firstName: "Titos",
    lastName: "Risebrow",
    age: 23,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 68,
    firstName: "Cordy",
    lastName: "Pitkeathly",
    age: 48,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 69,
    firstName: "Genvieve",
    lastName: "Carnoghan",
    age: 35,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 70,
    firstName: "Devina",
    lastName: "Jones",
    age: 18,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 71,
    firstName: "Ursa",
    lastName: "Dragon",
    age: 60,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 72,
    firstName: "Sonya",
    lastName: "Critch",
    age: 65,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 73,
    firstName: "Blair",
    lastName: "Cross",
    age: 22,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 74,
    firstName: "Marijo",
    lastName: "Bleasdille",
    age: 71,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 75,
    firstName: "Ignacius",
    lastName: "Sayer",
    age: 91,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 76,
    firstName: "Juan",
    lastName: "Baukham",
    age: 32,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 77,
    firstName: "Crin",
    lastName: "Belvard",
    age: 66,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 78,
    firstName: "Gerard",
    lastName: "Jacqueme",
    age: 39,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 79,
    firstName: "Kittie",
    lastName: "Loffhead",
    age: 49,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 80,
    firstName: "Butch",
    lastName: "Ong",
    age: 56,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 81,
    firstName: "Cordi",
    lastName: "Brecken",
    age: 54,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 82,
    firstName: "Julita",
    lastName: "McCray",
    age: 60,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 83,
    firstName: "Marnia",
    lastName: "Roycroft",
    age: 79,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 84,
    firstName: "Lionel",
    lastName: "Able",
    age: 28,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 85,
    firstName: "Jens",
    lastName: "Olenov",
    age: 59,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 86,
    firstName: "Jillayne",
    lastName: "Kittow",
    age: 83,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 87,
    firstName: "Cilka",
    lastName: "Aughtie",
    age: 76,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 88,
    firstName: "Dennison",
    lastName: "Burrage",
    age: 23,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 89,
    firstName: "Earle",
    lastName: "Windibank",
    age: 24,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 90,
    firstName: "Kasey",
    lastName: "Liversedge",
    age: 75,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 91,
    firstName: "Ty",
    lastName: "Cherrington",
    age: 94,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 92,
    firstName: "Aurel",
    lastName: "Euston",
    age: 51,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 93,
    firstName: "Em",
    lastName: "Axford",
    age: 55,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 94,
    firstName: "Alley",
    lastName: "Temblett",
    age: 51,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 95,
    firstName: "Gregoire",
    lastName: "Opie",
    age: 27,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 96,
    firstName: "Kevan",
    lastName: "Jacqueme",
    age: 66,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 97,
    firstName: "Elle",
    lastName: "Stelfax",
    age: 51,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 98,
    firstName: "Marlene",
    lastName: "Chattey",
    age: 83,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 99,
    firstName: "Perrine",
    lastName: "Januszkiewicz",
    age: 23,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 100,
    firstName: "Clarke",
    lastName: "Firpo",
    age: 74,
    gender: "Male",
    votedFor: "B",
  },
  {
    id: 29,
    firstName: "John",
    lastName: "Mike",
    age: 60,
    gender: "Male",
    votedFor: "A",
  },
  {
    id: 30,
    firstName: "Emilio",
    lastName: "Herrera",
    age: 60,
    gender: "Male",
    votedFor: "A",
  },
];

export const femaleVoters: any = [
  {
    id: 1,
    firstName: "Brynna",
    lastName: "Goranov",
    age: 78,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 3,
    firstName: "Margeaux",
    lastName: "Frape",
    age: 34,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 8,
    firstName: "Elicia",
    lastName: "Clowton",
    age: 47,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 10,
    firstName: "Juliane",
    lastName: "Plank",
    age: 90,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 11,
    firstName: "Thia",
    lastName: "Scrimshire",
    age: 81,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 14,
    firstName: "Cacilie",
    lastName: "Lydall",
    age: 75,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 16,
    firstName: "Terrie",
    lastName: "Keble",
    age: 78,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 19,
    firstName: "Allyn",
    lastName: "Patek",
    age: 43,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 27,
    firstName: "Dominique",
    lastName: "Way",
    age: 94,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 29,
    firstName: "Sherrie",
    lastName: "Dillaway",
    age: 37,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 31,
    firstName: "Eleanora",
    lastName: "Stearn",
    age: 56,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 32,
    firstName: "Kata",
    lastName: "Whitcher",
    age: 57,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 37,
    firstName: "Retha",
    lastName: "Mattessen",
    age: 84,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 38,
    firstName: "Nona",
    lastName: "Clayworth",
    age: 57,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 39,
    firstName: "Daisi",
    lastName: "Ruckert",
    age: 21,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 40,
    firstName: "Clemmy",
    lastName: "Pawellek",
    age: 64,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 42,
    firstName: "Gert",
    lastName: "Churn",
    age: 40,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 43,
    firstName: "Elsie",
    lastName: "Autrie",
    age: 63,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 44,
    firstName: "Ladonna",
    lastName: "Domeny",
    age: 18,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 46,
    firstName: "Fancie",
    lastName: "Piercy",
    age: 46,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 48,
    firstName: "Yalonda",
    lastName: "Edghinn",
    age: 45,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 50,
    firstName: "Jeane",
    lastName: "Rousby",
    age: 46,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 51,
    firstName: "Fayth",
    lastName: "Harmar",
    age: 76,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 57,
    firstName: "Gilemette",
    lastName: "Boagey",
    age: 92,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 60,
    firstName: "Lorne",
    lastName: "Simeoli",
    age: 30,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 62,
    firstName: "Freddi",
    lastName: "Stanistrete",
    age: 36,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 64,
    firstName: "Steffi",
    lastName: "Kier",
    age: 87,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 66,
    firstName: "Leila",
    lastName: "Ironmonger",
    age: 55,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 69,
    firstName: "Genvieve",
    lastName: "Carnoghan",
    age: 35,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 70,
    firstName: "Devina",
    lastName: "Jones",
    age: 18,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 71,
    firstName: "Ursa",
    lastName: "Dragon",
    age: 60,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 72,
    firstName: "Sonya",
    lastName: "Critch",
    age: 65,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 74,
    firstName: "Marijo",
    lastName: "Bleasdille",
    age: 71,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 77,
    firstName: "Crin",
    lastName: "Belvard",
    age: 66,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 79,
    firstName: "Kittie",
    lastName: "Loffhead",
    age: 49,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 81,
    firstName: "Cordi",
    lastName: "Brecken",
    age: 54,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 82,
    firstName: "Julita",
    lastName: "McCray",
    age: 60,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 83,
    firstName: "Marnia",
    lastName: "Roycroft",
    age: 79,
    gender: "Female",
    votedFor: "A",
  },
  {
    id: 86,
    firstName: "Jillayne",
    lastName: "Kittow",
    age: 83,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 87,
    firstName: "Cilka",
    lastName: "Aughtie",
    age: 76,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 90,
    firstName: "Kasey",
    lastName: "Liversedge",
    age: 75,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 92,
    firstName: "Aurel",
    lastName: "Euston",
    age: 51,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 93,
    firstName: "Em",
    lastName: "Axford",
    age: 55,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 97,
    firstName: "Elle",
    lastName: "Stelfax",
    age: 51,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 98,
    firstName: "Marlene",
    lastName: "Chattey",
    age: 83,
    gender: "Female",
    votedFor: "B",
  },
  {
    id: 99,
    firstName: "Perrine",
    lastName: "Januszkiewicz",
    age: 23,
    gender: "Female",
    votedFor: "B",
  },
];

export const votersWithFullName: any = [
  {
    fullName: "Brynna Goranov",
    id: 1,
    firstName: "Brynna",
    lastName: "Goranov",
    age: 78,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Tracey Manz",
    id: 2,
    firstName: "Tracey",
    lastName: "Manz",
    age: 79,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Margeaux Frape",
    id: 3,
    firstName: "Margeaux",
    lastName: "Frape",
    age: 34,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Ab Webb-Bowen",
    id: 4,
    firstName: "Ab",
    lastName: "Webb-Bowen",
    age: 27,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Walden Japp",
    id: 5,
    firstName: "Walden",
    lastName: "Japp",
    age: 80,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Goraud Warboys",
    id: 6,
    firstName: "Goraud",
    lastName: "Warboys",
    age: 73,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Vassili MacCrann",
    id: 7,
    firstName: "Vassili",
    lastName: "MacCrann",
    age: 87,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Elicia Clowton",
    id: 8,
    firstName: "Elicia",
    lastName: "Clowton",
    age: 47,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Olav Kleinstein",
    id: 9,
    firstName: "Olav",
    lastName: "Kleinstein",
    age: 74,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Juliane Plank",
    id: 10,
    firstName: "Juliane",
    lastName: "Plank",
    age: 90,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Thia Scrimshire",
    id: 11,
    firstName: "Thia",
    lastName: "Scrimshire",
    age: 81,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Nollie Walklot",
    id: 12,
    firstName: "Nollie",
    lastName: "Walklot",
    age: 31,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Sidnee Remer",
    id: 13,
    firstName: "Sidnee",
    lastName: "Remer",
    age: 74,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Cacilie Lydall",
    id: 14,
    firstName: "Cacilie",
    lastName: "Lydall",
    age: 75,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Jared Robez",
    id: 15,
    firstName: "Jared",
    lastName: "Robez",
    age: 47,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Terrie Keble",
    id: 16,
    firstName: "Terrie",
    lastName: "Keble",
    age: 78,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Timofei Nairy",
    id: 17,
    firstName: "Timofei",
    lastName: "Nairy",
    age: 18,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Holmes McColl",
    id: 18,
    firstName: "Holmes",
    lastName: "McColl",
    age: 18,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Allyn Patek",
    id: 19,
    firstName: "Allyn",
    lastName: "Patek",
    age: 43,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Dermot Fairfoull",
    id: 20,
    firstName: "Dermot",
    lastName: "Fairfoull",
    age: 55,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Archie Ponnsett",
    id: 21,
    firstName: "Archie",
    lastName: "Ponnsett",
    age: 75,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Barnard Poytheras",
    id: 22,
    firstName: "Barnard",
    lastName: "Poytheras",
    age: 37,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Montague Tennant",
    id: 23,
    firstName: "Montague",
    lastName: "Tennant",
    age: 75,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Lorne Guerreru",
    id: 24,
    firstName: "Lorne",
    lastName: "Guerreru",
    age: 71,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Royce Craiker",
    id: 25,
    firstName: "Royce",
    lastName: "Craiker",
    age: 90,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Stearn Mandeville",
    id: 26,
    firstName: "Stearn",
    lastName: "Mandeville",
    age: 88,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Dominique Way",
    id: 27,
    firstName: "Dominique",
    lastName: "Way",
    age: 94,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Alfredo Janas",
    id: 28,
    firstName: "Alfredo",
    lastName: "Janas",
    age: 60,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Sherrie Dillaway",
    id: 29,
    firstName: "Sherrie",
    lastName: "Dillaway",
    age: 37,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Noland Seckom",
    id: 30,
    firstName: "Noland",
    lastName: "Seckom",
    age: 85,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Eleanora Stearn",
    id: 31,
    firstName: "Eleanora",
    lastName: "Stearn",
    age: 56,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Kata Whitcher",
    id: 32,
    firstName: "Kata",
    lastName: "Whitcher",
    age: 57,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Ignazio Matuszynski",
    id: 33,
    firstName: "Ignazio",
    lastName: "Matuszynski",
    age: 79,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Free Dennant",
    id: 34,
    firstName: "Free",
    lastName: "Dennant",
    age: 51,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Nestor Piken",
    id: 35,
    firstName: "Nestor",
    lastName: "Piken",
    age: 75,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Shelton Blampied",
    id: 36,
    firstName: "Shelton",
    lastName: "Blampied",
    age: 52,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Retha Mattessen",
    id: 37,
    firstName: "Retha",
    lastName: "Mattessen",
    age: 84,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Nona Clayworth",
    id: 38,
    firstName: "Nona",
    lastName: "Clayworth",
    age: 57,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Daisi Ruckert",
    id: 39,
    firstName: "Daisi",
    lastName: "Ruckert",
    age: 21,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Clemmy Pawellek",
    id: 40,
    firstName: "Clemmy",
    lastName: "Pawellek",
    age: 64,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Johnny Boustead",
    id: 41,
    firstName: "Johnny",
    lastName: "Boustead",
    age: 45,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Gert Churn",
    id: 42,
    firstName: "Gert",
    lastName: "Churn",
    age: 40,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Elsie Autrie",
    id: 43,
    firstName: "Elsie",
    lastName: "Autrie",
    age: 63,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Ladonna Domeny",
    id: 44,
    firstName: "Ladonna",
    lastName: "Domeny",
    age: 18,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Mohandas Bullingham",
    id: 45,
    firstName: "Mohandas",
    lastName: "Bullingham",
    age: 20,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Fancie Piercy",
    id: 46,
    firstName: "Fancie",
    lastName: "Piercy",
    age: 46,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Urban Hedney",
    id: 47,
    firstName: "Urban",
    lastName: "Hedney",
    age: 96,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Yalonda Edghinn",
    id: 48,
    firstName: "Yalonda",
    lastName: "Edghinn",
    age: 45,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Webster Belvard",
    id: 49,
    firstName: "Webster",
    lastName: "Belvard",
    age: 98,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Jeane Rousby",
    id: 50,
    firstName: "Jeane",
    lastName: "Rousby",
    age: 46,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Fayth Harmar",
    id: 51,
    firstName: "Fayth",
    lastName: "Harmar",
    age: 76,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Fredrick Edworthye",
    id: 52,
    firstName: "Fredrick",
    lastName: "Edworthye",
    age: 85,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Arturo Trippitt",
    id: 53,
    firstName: "Arturo",
    lastName: "Trippitt",
    age: 91,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Rustie Duran",
    id: 54,
    firstName: "Rustie",
    lastName: "Duran",
    age: 79,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Pembroke Risebarer",
    id: 55,
    firstName: "Pembroke",
    lastName: "Risebarer",
    age: 60,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Graeme Chelnam",
    id: 56,
    firstName: "Graeme",
    lastName: "Chelnam",
    age: 87,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Gilemette Boagey",
    id: 57,
    firstName: "Gilemette",
    lastName: "Boagey",
    age: 92,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Witty Traise",
    id: 58,
    firstName: "Witty",
    lastName: "Traise",
    age: 96,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Garrick Gallehock",
    id: 59,
    firstName: "Garrick",
    lastName: "Gallehock",
    age: 41,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Lorne Simeoli",
    id: 60,
    firstName: "Lorne",
    lastName: "Simeoli",
    age: 30,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Kimball Tender",
    id: 61,
    firstName: "Kimball",
    lastName: "Tender",
    age: 60,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Freddi Stanistrete",
    id: 62,
    firstName: "Freddi",
    lastName: "Stanistrete",
    age: 36,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Manolo Duran",
    id: 63,
    firstName: "Manolo",
    lastName: "Duran",
    age: 35,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Steffi Kier",
    id: 64,
    firstName: "Steffi",
    lastName: "Kier",
    age: 87,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Eward Yakushkev",
    id: 65,
    firstName: "Eward",
    lastName: "Yakushkev",
    age: 83,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Leila Ironmonger",
    id: 66,
    firstName: "Leila",
    lastName: "Ironmonger",
    age: 55,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Titos Risebrow",
    id: 67,
    firstName: "Titos",
    lastName: "Risebrow",
    age: 23,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Cordy Pitkeathly",
    id: 68,
    firstName: "Cordy",
    lastName: "Pitkeathly",
    age: 48,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Genvieve Carnoghan",
    id: 69,
    firstName: "Genvieve",
    lastName: "Carnoghan",
    age: 35,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Devina Jones",
    id: 70,
    firstName: "Devina",
    lastName: "Jones",
    age: 18,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Ursa Dragon",
    id: 71,
    firstName: "Ursa",
    lastName: "Dragon",
    age: 60,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Sonya Critch",
    id: 72,
    firstName: "Sonya",
    lastName: "Critch",
    age: 65,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Blair Cross",
    id: 73,
    firstName: "Blair",
    lastName: "Cross",
    age: 22,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Marijo Bleasdille",
    id: 74,
    firstName: "Marijo",
    lastName: "Bleasdille",
    age: 71,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Ignacius Sayer",
    id: 75,
    firstName: "Ignacius",
    lastName: "Sayer",
    age: 91,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Juan Baukham",
    id: 76,
    firstName: "Juan",
    lastName: "Baukham",
    age: 32,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Crin Belvard",
    id: 77,
    firstName: "Crin",
    lastName: "Belvard",
    age: 66,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Gerard Jacqueme",
    id: 78,
    firstName: "Gerard",
    lastName: "Jacqueme",
    age: 39,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Kittie Loffhead",
    id: 79,
    firstName: "Kittie",
    lastName: "Loffhead",
    age: 49,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Butch Ong",
    id: 80,
    firstName: "Butch",
    lastName: "Ong",
    age: 56,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Cordi Brecken",
    id: 81,
    firstName: "Cordi",
    lastName: "Brecken",
    age: 54,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Julita McCray",
    id: 82,
    firstName: "Julita",
    lastName: "McCray",
    age: 60,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Marnia Roycroft",
    id: 83,
    firstName: "Marnia",
    lastName: "Roycroft",
    age: 79,
    gender: "Female",
    votedFor: "A",
  },
  {
    fullName: "Lionel Able",
    id: 84,
    firstName: "Lionel",
    lastName: "Able",
    age: 28,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Jens Olenov",
    id: 85,
    firstName: "Jens",
    lastName: "Olenov",
    age: 59,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Jillayne Kittow",
    id: 86,
    firstName: "Jillayne",
    lastName: "Kittow",
    age: 83,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Cilka Aughtie",
    id: 87,
    firstName: "Cilka",
    lastName: "Aughtie",
    age: 76,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Dennison Burrage",
    id: 88,
    firstName: "Dennison",
    lastName: "Burrage",
    age: 23,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Earle Windibank",
    id: 89,
    firstName: "Earle",
    lastName: "Windibank",
    age: 24,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Kasey Liversedge",
    id: 90,
    firstName: "Kasey",
    lastName: "Liversedge",
    age: 75,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Ty Cherrington",
    id: 91,
    firstName: "Ty",
    lastName: "Cherrington",
    age: 94,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Aurel Euston",
    id: 92,
    firstName: "Aurel",
    lastName: "Euston",
    age: 51,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Em Axford",
    id: 93,
    firstName: "Em",
    lastName: "Axford",
    age: 55,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Alley Temblett",
    id: 94,
    firstName: "Alley",
    lastName: "Temblett",
    age: 51,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Gregoire Opie",
    id: 95,
    firstName: "Gregoire",
    lastName: "Opie",
    age: 27,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Kevan Jacqueme",
    id: 96,
    firstName: "Kevan",
    lastName: "Jacqueme",
    age: 66,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "Elle Stelfax",
    id: 97,
    firstName: "Elle",
    lastName: "Stelfax",
    age: 51,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Marlene Chattey",
    id: 98,
    firstName: "Marlene",
    lastName: "Chattey",
    age: 83,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Perrine Januszkiewicz",
    id: 99,
    firstName: "Perrine",
    lastName: "Januszkiewicz",
    age: 23,
    gender: "Female",
    votedFor: "B",
  },
  {
    fullName: "Clarke Firpo",
    id: 100,
    firstName: "Clarke",
    lastName: "Firpo",
    age: 74,
    gender: "Male",
    votedFor: "B",
  },
  {
    fullName: "John Mike",
    id: 29,
    firstName: "John",
    lastName: "Mike",
    age: 60,
    gender: "Male",
    votedFor: "A",
  },
  {
    fullName: "Emilio Herrera",
    id: 30,
    firstName: "Emilio",
    lastName: "Herrera",
    age: 60,
    gender: "Male",
    votedFor: "A",
  },
];

export const votersByDecade = {
  "10": [
    {
      id: 17,
      firstName: "Timofei",
      lastName: "Nairy",
      age: 18,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 18,
      firstName: "Holmes",
      lastName: "McColl",
      age: 18,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 44,
      firstName: "Ladonna",
      lastName: "Domeny",
      age: 18,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 70,
      firstName: "Devina",
      lastName: "Jones",
      age: 18,
      gender: "Female",
      votedFor: "A",
    },
  ],
  "20": [
    {
      id: 45,
      firstName: "Mohandas",
      lastName: "Bullingham",
      age: 20,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 39,
      firstName: "Daisi",
      lastName: "Ruckert",
      age: 21,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 73,
      firstName: "Blair",
      lastName: "Cross",
      age: 22,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 67,
      firstName: "Titos",
      lastName: "Risebrow",
      age: 23,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 88,
      firstName: "Dennison",
      lastName: "Burrage",
      age: 23,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 99,
      firstName: "Perrine",
      lastName: "Januszkiewicz",
      age: 23,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 89,
      firstName: "Earle",
      lastName: "Windibank",
      age: 24,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 4,
      firstName: "Ab",
      lastName: "Webb-Bowen",
      age: 27,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 95,
      firstName: "Gregoire",
      lastName: "Opie",
      age: 27,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 84,
      firstName: "Lionel",
      lastName: "Able",
      age: 28,
      gender: "Male",
      votedFor: "A",
    },
  ],
  "30": [
    {
      id: 60,
      firstName: "Lorne",
      lastName: "Simeoli",
      age: 30,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 12,
      firstName: "Nollie",
      lastName: "Walklot",
      age: 31,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 76,
      firstName: "Juan",
      lastName: "Baukham",
      age: 32,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 3,
      firstName: "Margeaux",
      lastName: "Frape",
      age: 34,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 63,
      firstName: "Manolo",
      lastName: "Duran",
      age: 35,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 69,
      firstName: "Genvieve",
      lastName: "Carnoghan",
      age: 35,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 62,
      firstName: "Freddi",
      lastName: "Stanistrete",
      age: 36,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 22,
      firstName: "Barnard",
      lastName: "Poytheras",
      age: 37,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 29,
      firstName: "Sherrie",
      lastName: "Dillaway",
      age: 37,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 78,
      firstName: "Gerard",
      lastName: "Jacqueme",
      age: 39,
      gender: "Male",
      votedFor: "A",
    },
  ],
  "40": [
    {
      id: 42,
      firstName: "Gert",
      lastName: "Churn",
      age: 40,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 59,
      firstName: "Garrick",
      lastName: "Gallehock",
      age: 41,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 19,
      firstName: "Allyn",
      lastName: "Patek",
      age: 43,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 41,
      firstName: "Johnny",
      lastName: "Boustead",
      age: 45,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 48,
      firstName: "Yalonda",
      lastName: "Edghinn",
      age: 45,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 46,
      firstName: "Fancie",
      lastName: "Piercy",
      age: 46,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 50,
      firstName: "Jeane",
      lastName: "Rousby",
      age: 46,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 8,
      firstName: "Elicia",
      lastName: "Clowton",
      age: 47,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 15,
      firstName: "Jared",
      lastName: "Robez",
      age: 47,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 68,
      firstName: "Cordy",
      lastName: "Pitkeathly",
      age: 48,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 79,
      firstName: "Kittie",
      lastName: "Loffhead",
      age: 49,
      gender: "Female",
      votedFor: "B",
    },
  ],
  "50": [
    {
      id: 34,
      firstName: "Free",
      lastName: "Dennant",
      age: 51,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 92,
      firstName: "Aurel",
      lastName: "Euston",
      age: 51,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 94,
      firstName: "Alley",
      lastName: "Temblett",
      age: 51,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 97,
      firstName: "Elle",
      lastName: "Stelfax",
      age: 51,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 36,
      firstName: "Shelton",
      lastName: "Blampied",
      age: 52,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 81,
      firstName: "Cordi",
      lastName: "Brecken",
      age: 54,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 20,
      firstName: "Dermot",
      lastName: "Fairfoull",
      age: 55,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 66,
      firstName: "Leila",
      lastName: "Ironmonger",
      age: 55,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 93,
      firstName: "Em",
      lastName: "Axford",
      age: 55,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 31,
      firstName: "Eleanora",
      lastName: "Stearn",
      age: 56,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 80,
      firstName: "Butch",
      lastName: "Ong",
      age: 56,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 32,
      firstName: "Kata",
      lastName: "Whitcher",
      age: 57,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 38,
      firstName: "Nona",
      lastName: "Clayworth",
      age: 57,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 85,
      firstName: "Jens",
      lastName: "Olenov",
      age: 59,
      gender: "Male",
      votedFor: "A",
    },
  ],
  "60": [
    {
      id: 28,
      firstName: "Alfredo",
      lastName: "Janas",
      age: 60,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 55,
      firstName: "Pembroke",
      lastName: "Risebarer",
      age: 60,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 61,
      firstName: "Kimball",
      lastName: "Tender",
      age: 60,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 71,
      firstName: "Ursa",
      lastName: "Dragon",
      age: 60,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 82,
      firstName: "Julita",
      lastName: "McCray",
      age: 60,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 29,
      firstName: "John",
      lastName: "Mike",
      age: 60,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 30,
      firstName: "Emilio",
      lastName: "Herrera",
      age: 60,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 43,
      firstName: "Elsie",
      lastName: "Autrie",
      age: 63,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 40,
      firstName: "Clemmy",
      lastName: "Pawellek",
      age: 64,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 72,
      firstName: "Sonya",
      lastName: "Critch",
      age: 65,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 77,
      firstName: "Crin",
      lastName: "Belvard",
      age: 66,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 96,
      firstName: "Kevan",
      lastName: "Jacqueme",
      age: 66,
      gender: "Male",
      votedFor: "B",
    },
  ],
  "70": [
    {
      id: 24,
      firstName: "Lorne",
      lastName: "Guerreru",
      age: 71,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 74,
      firstName: "Marijo",
      lastName: "Bleasdille",
      age: 71,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 6,
      firstName: "Goraud",
      lastName: "Warboys",
      age: 73,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 9,
      firstName: "Olav",
      lastName: "Kleinstein",
      age: 74,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 13,
      firstName: "Sidnee",
      lastName: "Remer",
      age: 74,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 100,
      firstName: "Clarke",
      lastName: "Firpo",
      age: 74,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 14,
      firstName: "Cacilie",
      lastName: "Lydall",
      age: 75,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 21,
      firstName: "Archie",
      lastName: "Ponnsett",
      age: 75,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 23,
      firstName: "Montague",
      lastName: "Tennant",
      age: 75,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 35,
      firstName: "Nestor",
      lastName: "Piken",
      age: 75,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 90,
      firstName: "Kasey",
      lastName: "Liversedge",
      age: 75,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 51,
      firstName: "Fayth",
      lastName: "Harmar",
      age: 76,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 87,
      firstName: "Cilka",
      lastName: "Aughtie",
      age: 76,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 1,
      firstName: "Brynna",
      lastName: "Goranov",
      age: 78,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 16,
      firstName: "Terrie",
      lastName: "Keble",
      age: 78,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 2,
      firstName: "Tracey",
      lastName: "Manz",
      age: 79,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 33,
      firstName: "Ignazio",
      lastName: "Matuszynski",
      age: 79,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 54,
      firstName: "Rustie",
      lastName: "Duran",
      age: 79,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 83,
      firstName: "Marnia",
      lastName: "Roycroft",
      age: 79,
      gender: "Female",
      votedFor: "A",
    },
  ],
  "80": [
    {
      id: 5,
      firstName: "Walden",
      lastName: "Japp",
      age: 80,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 11,
      firstName: "Thia",
      lastName: "Scrimshire",
      age: 81,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 65,
      firstName: "Eward",
      lastName: "Yakushkev",
      age: 83,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 86,
      firstName: "Jillayne",
      lastName: "Kittow",
      age: 83,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 98,
      firstName: "Marlene",
      lastName: "Chattey",
      age: 83,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 37,
      firstName: "Retha",
      lastName: "Mattessen",
      age: 84,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 30,
      firstName: "Noland",
      lastName: "Seckom",
      age: 85,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 52,
      firstName: "Fredrick",
      lastName: "Edworthye",
      age: 85,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 7,
      firstName: "Vassili",
      lastName: "MacCrann",
      age: 87,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 56,
      firstName: "Graeme",
      lastName: "Chelnam",
      age: 87,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 64,
      firstName: "Steffi",
      lastName: "Kier",
      age: 87,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 26,
      firstName: "Stearn",
      lastName: "Mandeville",
      age: 88,
      gender: "Male",
      votedFor: "A",
    },
  ],
  "90": [
    {
      id: 10,
      firstName: "Juliane",
      lastName: "Plank",
      age: 90,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 25,
      firstName: "Royce",
      lastName: "Craiker",
      age: 90,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 53,
      firstName: "Arturo",
      lastName: "Trippitt",
      age: 91,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 75,
      firstName: "Ignacius",
      lastName: "Sayer",
      age: 91,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 57,
      firstName: "Gilemette",
      lastName: "Boagey",
      age: 92,
      gender: "Female",
      votedFor: "B",
    },
    {
      id: 27,
      firstName: "Dominique",
      lastName: "Way",
      age: 94,
      gender: "Female",
      votedFor: "A",
    },
    {
      id: 91,
      firstName: "Ty",
      lastName: "Cherrington",
      age: 94,
      gender: "Male",
      votedFor: "A",
    },
    {
      id: 47,
      firstName: "Urban",
      lastName: "Hedney",
      age: 96,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 58,
      firstName: "Witty",
      lastName: "Traise",
      age: 96,
      gender: "Male",
      votedFor: "B",
    },
    {
      id: 49,
      firstName: "Webster",
      lastName: "Belvard",
      age: 98,
      gender: "Male",
      votedFor: "A",
    },
  ],
};
